version: '3.7'

services:
  app:
    build: ./app
    container_name: 'app'
    restart: 'always'
    ports:
      - "5555:5555"
    expose:
      - '8000'


    environment:
      - "MARIADB_DATABASE=django_app"
      - "MARIADB_USER=django_user"
      - "MARIADB_PASSWORD=1234"
      - "MARIADB_HOST=mariadb"


    volumes:
    - type: 'bind'
      source: './volumes/app'
      target: '/app'

    - type: 'bind'
      source: './volumes/static'
      target: '/app/static'

    - type: 'bind'
      source: './volumes/media'
      target: '/app/media'
    depends_on:
      - "mariadb"
      - "nginx"




  mariadb:
    image: 'mariadb:latest'
    container_name: 'mariadb'
    restart: 'always'
    # port:
    #   -"8000:8000"
    expose:
      - '3306'
    environment:
      - "MARIADB_DATABASE=django_app"
      - "MARIADB_USER=django_user"
      - "MARIADB_PASSWORD=1234"
      - "MARIADB_ROOT_PASSWORD=1234"
    volumes:
    - type: 'bind'
      source: './volumes/dbdata'
      target: '/var/lib/mysql'




  nginx:
    build: ./nginx
    container_name: 'nginx'
    restart: 'always'
    ports:
      - '80:80'
    volumes:
    - type: 'bind'
      source: './volumes/media'
      target: '/app/media'

    - type: 'bind'
      source: './volumes/static'
      target: '/app/static'



  redis:
    image: redis:6.2-alpine
    restart: always
    expose:
      - '6379'
