# Generated by Django 4.0.4 on 2022-04-23 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_user_questions_user_isvaccinated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=500, validators=[django.core.validators.RegexValidator(message='Password must contain at least one uppercase letter.', regex='^(?=.*[A-Z])'), django.core.validators.RegexValidator(message='Password must contain at least one number.', regex='^(?=.*[0-9])'), django.core.validators.RegexValidator(message='Password must be eight characters or longer.', regex='^(?=.{8,})')]),
        ),
    ]
