# Generated by Django 4.0.4 on 2022-06-09 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DocAndPatient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmedicines',
            name='notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescriptionmedicines',
            name='nottakenno',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescriptionmedicines',
            name='period',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='prescriptionmedicines',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionmedicines',
            name='takenno',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('status', models.BooleanField(blank=True, default=None, null=True)),
                ('prescription_medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='DocAndPatient.prescriptionmedicines')),
            ],
        ),
    ]
