# Generated by Django 4.0.4 on 2022-05-07 17:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DocAndPatient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('A', 'Ampoule'), ('T', 'Tablet'), ('S', 'Syrup')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Medical_system_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='office_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='work_field',
        ),
        migrations.AddField(
            model_name='doctor',
            name='degree',
            field=models.CharField(blank=True, choices=[('GP', 'General Practitioner'), ('SP', 'Specialist'), ('SS', 'Sub-Specialist')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='field',
            field=models.CharField(blank=True, choices=[('CAR', 'Cardiologist'), ('NEU', 'Neurologist'), ('GYN', 'Geynecologist'), ('OBS', 'Obstetrician'), ('PED', 'Pediatrician'), ('URO', 'Urologists'), ('OTL', 'Otolaryngologist'), ('INF', 'Infection Disease'), ('INT', 'Internal Medicine'), ('SUR', 'Surgeon'), ('RAL', 'Radiologist'), ('RAT', 'Radiotherapy'), ('PHY', 'Physiologist'), ('ORT', 'Orthopedist'), ('PAT', 'Pathology')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='msn',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{10}$')]),
        ),
        migrations.AddField(
            model_name='doctor',
            name='officeno',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{11}$')]),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{11}$')]),
        ),
        migrations.CreateModel(
            name='PrescriptionMedicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.PositiveSmallIntegerField()),
                ('weeks', models.PositiveSmallIntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='DocAndPatient.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='DocAndPatient.prescription')),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptionsofdoc', to='DocAndPatient.doctor'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptionsofpatient', to=settings.AUTH_USER_MODEL),
        ),
    ]
