# Generated by Django 4.0.3 on 2022-03-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='user', to='User.question'),
        ),
    ]
